version: '3.8'

services:
  setorf-ui-app:
    image: ${DOCKER_IMAGE:-setorf-ui:latest}
    container_name: setorf-ui-app
    ports:
      - "8089:80"
    restart: unless-stopped
    networks:
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    external: true
